--- 
- name: SSH-KeyPair lab setup
  hosts: dev 
  tasks: 
  - name: Copying Sudoers file  
    copy: 
      src: /etc/sudoers.d/student
      dest: /etc/sudoers.d/student
      remote_src: yes

  - name: Copy authorized key 
    authorized_key: 
      user: student
      state: present
      key: "{{ lookup('file', '/home/student/.ssh/id_rsa.pub') }}"

