---
- name:
  hosts: dev
  gather_facts: false
  vars: 
  tasks:
  - name: add several users
    user:
      name: "{{ item.name }}"
      state: absent
      groups: "{{ item.groups }}"
    loop:
      - { name: 'testuser1', groups: 'wheel' }
      - { name: 'testuser2', groups: 'root' }

