---
- name: play with file modules 
  hosts: dev
  tasks: 
  - name: Create Ibm group 
    group:
      name: ibm 
      state: present 
  - name: create ravi user 
    user: 
      name: ravi 
      password: y69L38H/w5rTk
      update_password: always
      groups: ibm
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      state: present 
  - name: Set authorized key taken from file
    authorized_key:
      user: ravi
      state: present
      key: "{{ lookup('file', '/home/student/.ssh/id_rsa.pub') }}"
  - name: Copying sudoers entry
    copy: 
      content: "ravi  ALL=(ALL) NOPASSWD: ALL"
      dest: /etc/sudoers.d/ravi

      
